"""
POS Email Service
Handles sending of automated POS reports via Email.
"""
import smtplib
import ssl
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from flask import render_template

from app.routes.pos.core import get_pos_setting
from app.services.pos_reports import generate_daily_report_data
from app.services.security import decrypt

logger = logging.getLogger(__name__)

def send_eod_email(report_date):
    """
    Send the End of Day report email for a specific date.
    Args:
        report_date (date): Local date to report on.
    Returns:
        bool: True if sent successfully, False otherwise.
    """
    # 1. Check if configured
    host = get_pos_setting('POS_EMAIL_HOST')
    recipients = get_pos_setting('POS_EMAIL_RECIPIENTS')
    
    if not host or not recipients:
        logger.warning("POS EOD Email skipped: Missing host or recipients configuration.")
        return False

    try:
        # 2. Generate Data
        data = generate_daily_report_data(report_date)
        
        # 3. Create Email Content
        # We can reuse the daily_report template or a simplified email version.
        # For simplicity and style, let's create a minimal HTML string or use a dedicated template.
        # Using a dedicated template is cleaner, let's assume we create one or render the existing one with a flag.
        
        # Render HTML body
        # We need an app context for render_template if not already in one (Background tasks might need manual context)
        # But assuming this is called from a context-aware place or we push one.
        # Note: If called from background thread, we need 'with app.app_context():' there.
        
        subject = f"End of Day Report - {report_date.strftime('%Y-%m-%d')}"
        
        # Simple HTML Construction (Robust fallback if template rendering is complex in background)
        html_content = f"""
        <html>
        <body>
            <h2>End of Day Report: {report_date.strftime('%Y-%m-%d')}</h2>
            <hr>
            <h3>Summary</h3>
            <p><strong>Gross Sales:</strong> ${data['summary']['gross_sales']:.2f}</p>
            <p><strong>Discounts:</strong> -${data['summary']['total_discounts']:.2f}</p>
            <p><strong>Refunds:</strong> -${data['refunds']['total']:.2f}</p>
            <p><strong>Net Revenue:</strong> ${data['net_revenue']:.2f}</p>
            <p><strong>Total Orders:</strong> {data['summary']['total_orders']}</p>
            
            <h3>Payment Breakdown</h3>
            <ul>
        """
        
        for p in data['payments']:
            html_content += f"<li>{p['payment_method'].title()}: ${p['total_amount']:.2f} ({p['count']} orders)</li>"
            
        html_content += """
            </ul>
            <p><em>Autogenerated by RSCP POS</em></p>
        </body>
        </html>
        """
        
        # 4. Send Email
        port = int(get_pos_setting('POS_EMAIL_PORT') or '587')
        user = get_pos_setting('POS_EMAIL_USER')
        password_enc = get_pos_setting('POS_EMAIL_PASSWORD')
        password = decrypt(password_enc) if password_enc else None

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = user or 'noreply@rscp.local'
        msg["To"] = recipients
        
        part = MIMEText(html_content, "html")
        msg.attach(part)
        
        context = ssl.create_default_context()
        
        with smtplib.SMTP(host, port) as server:
            server.starttls(context=context)
            if user and password:
                server.login(user, password)
            
            # recipients can be comma separated
            recipient_list = [r.strip() for r in recipients.split(',') if r.strip()]
            server.sendmail(user, recipient_list, msg.as_string())
            
        logger.info(f"POS EOD Email sent to {recipients}")
        return True

    except Exception as e:
        logger.error(f"Failed to send POS EOD Email: {e}")
        return False
